[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Headers para optimización
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers para recursos estáticos
[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/icons/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers para PWA
[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# URLs limpias para artículos (rewrite interno)
[[redirects]]
  from = "/articulos/fases-sueno"
  to = "/articles/como-funciona-el-sueno-fases-etapas.html"
  status = 200

[[redirects]]
  from = "/articulos/horas-sueno-por-edad"
  to = "/articles/cuantas-horas-dormir-segun-edad.html"
  status = 200

# Redirecciones 301 de URLs antiguas a nuevas (para SEO)
[[redirects]]
  from = "/articles/como-funciona-el-sueno-fases-etapas.html"
  to = "/articulos/fases-sueno"
  status = 301

[[redirects]]
  from = "/articles/cuantas-horas-dormir-segun-edad.html"
  to = "/articulos/horas-sueno-por-edad"
  status = 301

# Redirección general para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuración de funciones (opcional)
[functions]
  directory = "netlify/functions"
